import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { auth } from "@/auth";
import { UserProvider } from "@/context/UserProvider";

export const metadata: Metadata = {
  title: "Infra Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch the session server-side
  const session = await auth();
  const user = session?.user
    ? {
        id: session.user.id!,
        name: session.user.name ?? "",
        email: session.user.email ?? "",
        recentActivity: [],
        documents: [],
        projects: [],
        apiRequests: [],
      }
    : null;

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UserProvider user={user}>
          {children}
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
